apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: test-
resources:
- frontend.yaml
- vs-frontend.yaml

vars:
- name: MY_SERVICE_NAME
  objref:
    kind: Service
    name: frontend-service
    apiVersion: v1
