apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-vs
spec:
  hosts:
    - "awsdevmanagedorg.sreyo.in"
  gateways:
    - gateway
  http:
    - route:
        - destination:
            host: $(MY_SERVICE_NAME).default.svc.cluster.local
            port:
              number: 8081
            #subset: v2